config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

ThirtyTwoPages::Application.routes.draw do

  root :to => "users#show"

  devise_for :users

  resources :users do
    resource :profile
    resources :friend_requests, :only => [:index, :new, :create, :update] do
      collection do
        get "refresh"
      end
    end
    resources :friendships, :only => [:new, :create, :destroy]
    resources :messages
    resources :notifications
    resources :photos
    resources :projects, :only => [:index, :show]
  end

  resources :projects, :except => [:index, :show] do
    resources :pages
    resources :images
		resources :likes
  end

  resources :pages do
    resource :caption
		resource :image
  end

  resources :posts do
    collection do
      get "refresh"
    end
    resources :comments do
      collection do
        get "refresh"
      end
    end
    resources :likes do
      collection do
        get "refresh"
      end
    end
  end

  resources :emails

	resources :user_searches, :only => [:new, :create, :show]
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :subject, :content, :sender_id, :recipient_id, :read

  belongs_to :sender, :class_name => "User", :foreign_key => :sender_id
  belongs_to :recipient, :class_name => "User", :foreign_key => :recipient_id

  validates :sender_id, :recipient_id, :presence => true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @sent_messages = current_user.sent_messages.order("id DESC")
    @rec_messages = current_user.rec_messages("id DESC")
  end

  def new
    @message = current_user.sent_messages.build
    @users = current_user.friends.map { |user| [user.full_name, user.id] }
  end

  def create
    @message = current_user.sent_messages.build(params[:message])
    @message.read = false

    if @message.save
      notif = @message.recipient.notifications.build(
                          :content => "#{@message.sender.full_name} has sent you a message.",
                          :read => false
                          )
                          notif.save
      redirect_to user_message_url(@message.sender, @message)
    else
      render :new
    end
  end

  def show
    @message = Message.find(params[:id])
    @message.read = true if @message.recipient_id == current_user.id
    @message.save
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/views/messages/_inbox.html.erb
<% current_user.rec_messages.each do |m| %>
  <li class="rec-message">
    <span class="rec-message-sender"><%= link_to m.sender.full_name, user_url(m.sender) %></span>
    <span class="rec-message-subject"><%= link_to m.subject, user_message_url(m.sender.id, m.id) %></span>
  </li>
<% end %>

app/views/messages/index.html.erb
<%= button_to "Compose a message", new_user_message_url(current_user), :method => :get %>

<section class="rec-messages">
  <h2>Inbox</h2>
  <% @rec_messages.each do |m| %>
    <div class="rec-message">
      <span class="rec-message-sender"><%= link_to m.sender.full_name, user_url(m.sender) %></span>
      <span class="rec-message-subject"><%= link_to m.subject, user_message_url(m.sender.id, m.id) %></span>
      <span class="rec-message-date"><%= m.created_at.to_formatted_s(:long) %></span>
    </div>
  <% end %>
</section>

<section class="sent-messages">
  <h2>Outbox</h2>
  <% @sent_messages.each do |m| %>
    <div class="sent-message">
      <span class="sent-message-sender"><%= link_to m.recipient.full_name, user_url(m.recipient) %></span>
      <span class="sent-message-subject"><%= link_to m.subject, user_message_url(m.sender.id, m.id) %></span>
      <span class="sent-message-date"><%= m.created_at.to_formatted_s(:long) %></span>
    </div>
  <% end %>
</section>

app/views/messages/new.html.erb
<h2>Compose your message!</h2>

<%= form_for @message, :url => user_messages_url(current_user), :method => :post do |f| %>

  <%= f.label "To" %>
  <%= f.select(:recipient_id, @users) %><br>

  <%= f.label :subject %>
  <%= f.text_field :subject %><br>

  <%= f.label :content %><br>
  <%= f.text_area :content %><br>

  <%= f.submit "SEND" %>

<% end %>

app/views/messages/show.html.erb
<h2>Subject: <%= @message.subject %></h2>
<h3>From: <%= link_to @message.sender.full_name, user_url(@message.sender) %></h3>

<%= @message.content %>