config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

ThirtyTwoPages::Application.routes.draw do

  root :to => "users#show"

  devise_for :users

  resources :users do
    resource :profile
    resources :friend_requests, :only => [:index, :new, :create, :update] do
      collection do
        get "refresh"
      end
    end
    resources :friendships, :only => [:new, :create, :destroy]
    resources :messages
    resources :notifications
    resources :photos
    resources :projects, :only => [:index, :show]
  end

  resources :projects, :except => [:index, :show] do
    resources :pages
    resources :images
		resources :likes
  end

  resources :pages do
    resource :caption
		resource :image
  end

  resources :posts do
    collection do
      get "refresh"
    end
    resources :comments do
      collection do
        get "refresh"
      end
    end
    resources :likes do
      collection do
        get "refresh"
      end
    end
  end

  resources :emails

	resources :user_searches, :only => [:new, :create, :show]
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :user_id, :content, :read

  belongs_to :user
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = current_user.notifications.order("id DESC")
    @notifications.update_all(:read => true)
  end

  def create
  end

  def destroy
  end

end

app/views/notifications/_list.html.erb
<% current_user.notifications.order("id DESC").each do |n| %>
<li>
  <article class="notification"><%= link_to n.content, user_notifications_url(current_user) %></article>
</li>
<% end %>

app/views/notifications/index.html.erb
<section class="notifications">
  <h2>Notifications</h2>
  <% @notifications.each do |n| %>
    <article class="notification"><%= n.content %></article>
  <% end %>
</section>