config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

ThirtyTwoPages::Application.routes.draw do

  root :to => "users#show"

  devise_for :users

  resources :users do
    resource :profile
    resources :friend_requests, :only => [:index, :new, :create, :update] do
      collection do
        get "refresh"
      end
    end
    resources :friendships, :only => [:new, :create, :destroy]
    resources :messages
    resources :notifications
    resources :photos
    resources :projects, :only => [:index, :show]
  end

  resources :projects, :except => [:index, :show] do
    resources :pages
    resources :images
		resources :likes
  end

  resources :pages do
    resource :caption
		resource :image
  end

  resources :posts do
    collection do
      get "refresh"
    end
    resources :comments do
      collection do
        get "refresh"
      end
    end
    resources :likes do
      collection do
        get "refresh"
      end
    end
  end

  resources :emails

	resources :user_searches, :only => [:new, :create, :show]
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :user_id, :title, :description, :public, :thumbnail,
                  :self_ends, :trim_height, :trim_width, :page_count

  belongs_to :user
  has_attached_file :thumbnail, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_many :pages, :dependent => :destroy
  has_many :images, :dependent => :destroy
	has_many :posts, :dependent => :destroy
	has_many :likes, :dependent => :destroy

  validates :user_id, :title, :presence => true
  validates :public, :inclusion => { :in => [true, false] }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:show]

  def index
    @projects = current_user.projects
    @user = User.find(params[:user_id])
  end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(params[:project])

    @project.page_count.times do |i|
      page = @project.pages.build(:number => i + 1)
      page.save
      caption = page.build_caption(:content => "(page #{i + 1} text)")
      caption.save
      image = page.build_image(:file => nil)
      image.save
    end

    if @project.save
      redirect_to user_project_url(current_user, @project)
    else
      render :new
    end
  end

  def show
    @project = Project.includes(:pages => [:caption, :image]).find(params[:id])
    @image = @project.images.build
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      redirect_to user_project_url(current_user, @project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])


  end

end

app/views/projects/_form.html.erb
<%= f.label :title %>
<%= f.text_field :title %><br>

<%= f.label :description %><br>
<%= f.text_area :description %><br>


<%= f.label :page_count %>
<%= f.select(:page_count, options_for_select( [32, 40] )) %><br>

<%= f.label :trim_width, "width", :class => "number-field" %>
<%= f.text_field :trim_width %><br>

<%= f.label :trim_height, "height", :class => "number-field" %>
<%= f.text_field :trim_height %><br>

<%= f.label :self_ends_true, "Self-ends" %>
<%= f.radio_button :self_ends, true %>
<%= f.label :self_ends_false, "Colored ends" %>
<%= f.radio_button :self_ends, false %><br>


<!-- nested form here for manuscript, images -->

<%= f.label :thumbnail, "Thumbnail image" %><br>
<div id="photo-attachment-container">
  choose file
  <div class="wrapper">
    <%= f.file_field :thumbnail %>
  </div>
</div>
<span class="photo-file-name">
</span>
<br>

<%= f.label :public_false, "Keep my project private for now." %>
<%= f.radio_button :public, false %><br>
<%= f.label :public_true, "Show it to the world!" %>
<%= f.radio_button :public, true %><br>

app/views/projects/_list.html.erb
<section class="projects">
  <% unless projects.empty? %>
    <h2>Projects</h2>
    <% projects.each do |p| %>
  		<div class="project-thumb">
  		  <a href="<%= user_project_url(p.user, p) %>">
  				<figure>
  		      <% if p.thumbnail.blank? %>
  		        <div class="project-thumbnail-blank">?</div>
  		      <% else%>
  		        <%= image_tag p.thumbnail.url(:thumb) %>
  		      <% end %>
  		      <figcaption><%= p.title %></figcaption>
  		    </figure>
  			</a>
  		</div>
  	<% end %>
  <% end %>
</section>

app/views/projects/edit.html.erb
<div class="project-edit">
  <h2>Edit your project</h2>
  <%= form_for @project, :url => project_path(@project), :method => :put do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>

  <%= f.submit "edit project" %>
  <% end %>
</div>

app/views/projects/index.html.erb
<div class="projects-index">
  <h2>Projects</h2>
  <% if @user == current_user %>
    <%= link_to "Make new project", new_project_url %>
  <% end %>
  <%= render :partial => "list", :locals => {:projects => @user.projects} %>
</div>

app/views/projects/new.html.erb
<div class="project-new">
  <h2>Make new project</h2>
  <%= form_for @project do |f| %>
    <%= render :partial => "form", :locals => {:f => f} %>

    <%= f.submit "submit project" %>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="project">
  <div class="project-user">
   <a href="<%= user_url(@project.user) %>"><%= image_tag @project.user.avatar.url(:bitty) %></a>
   <span class="project-user-name"><%= @project.user.full_name %></span>
  </div>
	<h1 class="project-title"><%= @project.title %></h1>
	<section class="project-likes-list">
    <% if signed_in? %>
		  <span class="project-add-like"><% unless current_user.likes_project?(@project) %><%= link_to "LIKE", project_likes_url(@project), :method => :post %><% end %></span>
		  <span class="project-likes"><% unless @project.likes.length == 0 %><%= @project.likes.length %> people like this project<% end %></span>
    <% end %>
	</section>
  <div class="project-description">
    <%= @project.description %>
  </div>

  <% if signed_in? && current_user == @project.user %>
    <div class="project-edit">
      <h2><%= link_to "Edit this project", edit_project_url(@project) %><h2>
    </div>
  <% end %>

  <div class="project-dummy">
    <div class="sidebar">
      <% if @project.user == current_user %>
        <%= render :partial => "images/sidebar", :locals => { :images => @project.images.reverse, :image => @image } %>
      <% end %>
    </div>
    <%= render :partial => "pages/template_two", :locals => { :project => @project, :image => @image } %>
  </div>

</div>

<% if signed_in? %>
  <section class="project-timeline">
  	<h2>comment on this project</h2>
    <%= render :partial => "posts/form", :locals => {:project_id => @project.id} %>
    <%= render :partial => "posts/list", :locals => {:posts => @project.posts.order("id DESC")} %>
  </section>
<% end %>


<section class="project-email">
  <h2>tell someone about it!</h2>
  <%= render :partial => "emails/form" %>
</section>