config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

ThirtyTwoPages::Application.routes.draw do

  root :to => "users#show"

  devise_for :users

  resources :users do
    resource :profile
    resources :friend_requests, :only => [:index, :new, :create, :update] do
      collection do
        get "refresh"
      end
    end
    resources :friendships, :only => [:new, :create, :destroy]
    resources :messages
    resources :notifications
    resources :photos
    resources :projects, :only => [:index, :show]
  end

  resources :projects, :except => [:index, :show] do
    resources :pages
    resources :images
		resources :likes
  end

  resources :pages do
    resource :caption
		resource :image
  end

  resources :posts do
    collection do
      get "refresh"
    end
    resources :comments do
      collection do
        get "refresh"
      end
    end
    resources :likes do
      collection do
        get "refresh"
      end
    end
  end

  resources :emails

	resources :user_searches, :only => [:new, :create, :show]
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :user_id, :project_id

  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy
	belongs_to :project

  accepts_nested_attributes_for :comments, :allow_destroy => true

  # validates :content, :user_id, :presence => true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(:content => params[:content], :project_id => params[:project_id])
    @post.save
    render :nothing => true
  end

  def show
    @post = Post.last
  end

  def refresh
    @post = Post.last
    render :layout => false
  end

end

app/views/posts/_form.html.erb
<section class="new-post-form">
  <%= form_for Post.new, :remote => true do |f| %>

    <article>
    	<%= f.text_area :content %>
		</article>

    <article>
			<%= f.hidden_field :project_id, :value => project_id %>
    </article>

    <article class="button">
		  be heard
    </article>

  <% end %>
</section>

app/views/posts/_list.html.erb
<section class="posts">
  <% posts.each do |p| %>
    <article class="post">
      <div class="post-main">
        <div class="post-avatar">
					<a href="<%= user_url(p.user) %>">
						<% if !p.user.avatar_file_name.blank? %>
							<%= image_tag p.user.avatar.url(:bitty) %>
						<% else %>
							<div class="user-avatar-bitty-blank">?</div>
						<% end %>
					</a>
			  </div>
        <div class="post-main-container">
          <span class="post-user"><%= p.user.full_name %></span>
          <span class="post-date"><%= time_ago_in_words(p.created_at) %> ago</span>
          <div class="post-content"><%= p.content %></div>
          <div class="footer">
            <span class="post-add-comment"><button class="button button-sm on-button">comment</button></span>
            <span class="post-add-like"><% unless current_user.likes_post?(p) %><%= button_to "like", post_likes_url(p), :class => "button button-sm" %><% end %></span>
            <span class="post-likes"><% unless p.likes.length == 0 %><%= p.likes.length %> people like this post<% end %></span>
            <%= render :partial => "comments/form", :locals => { :post => p } %>
          </div>
          <article class="post-comments"><%= render :partial => "comments/list", :locals => { :post => p, :comments => p.comments } %></article>
        </div>
      </div>
    </article>
  <% end %>
</section>

app/views/posts/index.html.erb
<%= render :partial => "list", :locals => {:posts => @posts.reverse} %>

app/views/posts/refresh.html.erb
<div class="post-main">
  <div class="post-avatar">
		<a href="<%= user_url(@post.user) %>">
			<% if !@post.user.avatar_file_name.blank? %>
				<%= image_tag @post.user.avatar.url(:bitty) %>
			<% else %>
				<div class="user-avatar-bitty-blank">?</div>
			<% end %>
		</a>
  </div>
  <div class="post-main-container">
    <span class="post-user"><%= @post.user.full_name %></span>
    <span class="post-date"><%= time_ago_in_words(@post.created_at) %> ago</span>
    <div class="post-content"><%= @post.content %></div>
    <div class="footer">
      <span class="post-add-comment"><button class="button button-sm">comment</button></span>
      <span class="post-add-like"><% unless current_user.likes_post?(@post) %><%= button_to "like", post_likes_url(@post), :class => "button button-sm" %><% end %></span>
      <span class="post-likes"><% unless @post.likes.length == 0 %><%= @post.likes.length %> people like this post<% end %></span>
      <%= render :partial => "comments/form", :locals => { :post => @post } %>
    </div>
    <article class="post-comments"><%= render :partial => "comments/list", :locals => { :post => @post, :comments => @post.comments } %></article>
  </div>
</div>

app/views/posts/show.html.erb
<article class="post">
  <div class="post-main">
	  <div class="post-avatar">
			<a href="<%= user_url(@post.user) %>">
				<% if !@post.user.avatar_file_name.blank? %>
					<%= image_tag @post.user.avatar.url(:bitty) %>
				<% else %>
					<div class="user-avatar-bitty-blank">?</div>
				<% end %>
			</a>
	  </div>
		<span class="post-user"><%= @post.user.full_name %></span>
    <span class="post-date"><%= time_ago_in_words(@post.created_at) %> ago</span>
    <div class="post-content"><%= @post.content %></div>
  </div>
  <div class="footer">
    <span class="post-add-comment"><%= link_to "COMMENT", new_post_comment_url(@post) %></span>
    <span class="post-add-like"><% unless current_user.likes_post?(@post) %><%= link_to "LIKE", post_likes_url(@post), :method => :post %><% end %></span>
    <span class="post-likes"><% unless @post.likes.length == 0 %><%= @post.likes.length %> people like this post<% end %></span>
  </div>
  <article class="post-comments"><%= render :partial => "comments/list", :locals => { :comments => @post.comments } %></article>
</article>